import type { BootstrapResponse } from '../types';

export const fallbackBootstrap: BootstrapResponse = {
  profile: {
    name: 'Sentinel Overseer',
    role: 'System Administrator',
    status: 'Offline Demo',
  },
  selectedRoleId: null,
  selectedScreen: 'onboarding',
  roles: [
    { id: 'cyclist', name: 'Cyclist', description: 'Bike lanes and road hazards', icon: '🚲', accent: '#46f1c5' },
    { id: 'escooter', name: 'E-Scooter', description: 'Shared path alerts', icon: '🛴', accent: '#b7c6f3' },
    { id: 'pedestrian', name: 'Pedestrian', description: 'Sidewalk and crossing safety', icon: '🚶', accent: '#ffcf96' },
    { id: 'wheelchair', name: 'Wheelchair', description: 'Accessible route priority', icon: '♿', accent: '#ffddb8' },
    {
      id: 'visually_impaired',
      name: 'Visually Impaired',
      description: 'Audio-first alerts',
      icon: '👁️',
      accent: '#f59e0b',
      highlight: true,
    },
    { id: 'driver', name: 'Driver', description: 'Bike lane obstruction reporting', icon: '🚗', accent: '#a9b7e4' },
  ],
  hazards: [
    {
      id: 'haz-1',
      title: 'Vehicle in Bike Lane',
      summary: 'Delivery van blocking protected lane near junction.',
      category: 'Vehicle',
      distance: '45m ahead',
      severity: 'critical',
      status: 'active',
      recommendation: 'Merge left onto footpath and re-enter after junction.',
      createdAt: '2 min ago',
      confidence: 94,
      position: { top: '35%', left: '60%' },
    },
    {
      id: 'haz-2',
      title: 'Pothole Identified',
      summary: 'Road depression on eastbound lane.',
      category: 'Surface',
      distance: '80m ahead',
      severity: 'medium',
      status: 'watch',
      recommendation: 'Slow down and move to the inner lane.',
      createdAt: '8 min ago',
      confidence: 88,
      position: { top: '52%', left: '65%' },
    },
    {
      id: 'haz-3',
      title: 'Sidewalk Construction',
      summary: 'Temporary barriers interrupt pedestrian route.',
      category: 'Construction',
      distance: '200m ahead',
      severity: 'low',
      status: 'active',
      recommendation: 'Follow highlighted detour to parallel street.',
      createdAt: '15 min ago',
      confidence: 91,
      position: { top: '75%', left: '45%' },
    },
  ],
  alerts: [
    {
      id: 'alert-1',
      title: 'Offline mode',
      detail: 'Running with fallback data because API is unavailable.',
      time: 'Now',
      tone: 'warning',
    },
    {
      id: 'alert-2',
      title: 'Route protected',
      detail: 'A safer turn is available 60 meters ahead.',
      time: '1 min',
      tone: 'success',
    },
  ],
  stats: {
    avoidedHazards: 47,
    saferKm: 1.2,
    reportsSent: 12,
    accuracy: 89,
    liveCommuters: 328,
    weeklyReports: [12, 18, 26, 15, 20, 10, 8],
  },
  settings: {
    highContrast: true,
    audioAlerts: true,
    screenReader: false,
    liveBroadcast: true,
    interfaceScale: 'L',
    voiceVolume: 85,
    speechSpeed: 'normal',
    detectionRadius: 50,
    cadence: 'immediate',
  },
};
